name: Build and Publish to PyPI

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup ccache
        if: runner.os != 'Windows'
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1
        env:
          CIBW_BEFORE_ALL_LINUX: yum install -y ccache
          CIBW_BEFORE_ALL_MACOS: brew install libomp ccache
          CIBW_BUILD_FRONTEND: pip
          CIBW_ENVIRONMENT_LINUX: >
            PATH="$PATH:/usr/lib64/ccache:/usr/lib/ccache"
            CMAKE_CXX_COMPILER_LAUNCHER=ccache
          CIBW_ENVIRONMENT_MACOS: >
            PATH="$PATH:/usr/local/opt/ccache/libexec"
            CMAKE_CXX_COMPILER_LAUNCHER=ccache
          CIBW_ENVIRONMENT_WINDOWS: >
            CMAKE_CXX_COMPILER_LAUNCHER=ccache

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build sdist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nn-engine-core
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1